# Generated by Django 6.0.7 on 2026-07-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('especialidade', models.CharField(max_length=100)),
                ('registro_profissional', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_configurados', to='profissionais.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais_configurados', to='servicos.servico')),
            ],
            options={
                'ordering': ['profissional', 'servico'],
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='profissionais', through='profissionais.ProfissionalServico', to='servicos.servico'),
        ),
        migrations.AddConstraint(
            model_name='profissionalservico',
            constraint=models.UniqueConstraint(fields=('profissional', 'servico'), name='profissional_servico_unico'),
        ),
    ]
