# Generated by Django 6.0.7 on 2026-07-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(choices=[('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICAO', 'Nutrição'), ('PSICOLOGIA', 'Psicologia'), ('ODONTOLOGIA', 'Odontologia'), ('MEDICINA', 'Medicina'), ('DERMATOLOGIA', 'Dermatologia'), ('ENFERMAGEM', 'Enfermagem'), ('FONOAUDIOLOGIA', 'Fonoaudiologia'), ('TERAPIA_OCUPACIONAL', 'Terapia Ocupacional'), ('OUTRA', 'Outra')], max_length=50),
        ),
    ]
