# Generated by Django 6.0.7 on 2026-08-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0003_agendamento_duracao_minutos'),
        ('pacientes', '0001_initial'),
        ('profissionais', '0002_alter_profissional_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20)),
                ('queixa_principal', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('conduta', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento', to='agendamentos.agendamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='profissionais.profissional')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
    ]
