# Generated by Django 6.0.7 on 2026-07-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('profissional', 'data', 'horario'), name='unique_profissional_horario'),
        ),
    ]
