# Generated by Django 6.0.7 on 2026-07-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_unique_profissional_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
