# Generated by Django 6.0.7 on 2026-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_criar_grupos'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECEPCAO', 'Recepção'), ('PROFISSIONAL', 'Profissional'), ('FINANCEIRO', 'Financeiro')], default='RECEPCAO', max_length=20),
        ),
    ]
