# Generated by Django 6.0.7 on 2026-08-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_duracao_minutos'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacao_financeira', to='agendamentos.agendamento'),
        ),
    ]
